### ISSUE TITLE
code and paper consistency.

### ISSUE THREAD

**Issue by tuvovan** [sanghviyashiitb/poisson-deblurring#4]
Hello,

I have a question regarding to what was in the paper and what is in the code.

In the paper, the output is X, but in your code [here](https://github.com/sanghviyashiitb/poisson-deblurring/blob/3008c195bc8478bacacbf615a54e60a9e1246bcb/models/network_p4ip.py#L168) output was z. Can you please explain this? 

thank you!

**Comment by sanghviyashiitb** [comment]
Hi, 
Firstly, I apologize for the late response. 

Thank you for pointing out the inconsistency in the code and the paper. Since the model was trained and tested to give output as 'z', I don't expect the results to change from the ones provided in the paper. 

Next since we're using the denoiser output instead of the x-stage deblurring as the final output, I suspect the network should get a little 'boost' in performance. However, I haven't verified this experimentally.
